# Generated by Django 4.2 on 2024-10-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_alter_article_number_of_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
    ]
